### ISSUE TITLE
HTTPError = Erreur dans l'URL

### ISSUE THREAD

**Issue by lunarok** [h4wkmoon/xbmc-domoticz#7]
Hi,

I get this error message after configuring the URL of Domoticz server.
I try :
http://ip:8080/
ip:8080

None working. Using XBMC 13 RC on a RaspBMC if it can helps.

Thanks, your plugin look promising for an installation with Domoticz

Cédric

**Comment by h4wkmoon** [comment]
I should make the code more adaptative and support several way to set the serveur url. 
But I don't use the add-on anymore, nore do I maintain it.
If someone is interested, please do.
